# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c96973b9c82c09599a524db6098562551c80f977496f2618491c37a0bac08bbceded3fe99786c967abc68762b53e36348d35687f061549488a1f29f69caeff

test:
  secret_key_base: f484490001219fcc3266f9f5576f35f2f5b2544529cc8c02139d0721136d517b265523d4e99e1b649c75a2935d96cb2b5edf517ed4ff6a97485effc2d2ec3fc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
